# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # 触发构建的动作和对应的分支，代码在哪，分支就配置哪。
  # 这里是master分支，所以每次push到master分支，就会触发构建。
  push:
    branches: [master]
  # pull_request 也会触发构建
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup install env
        env:
          # 需要在 secrets 创建该变量 ACTION_DEPLOY_KEY
          # 并且把你本地计算机的私钥复制进去，和用户设置里的`SSH keys` 保持一致
          # 方便后续，构建完成后，推送代码到gh-pages分支。
          ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}

        run: |
          # set up private key for deploy
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      # Runs a set of commands using the runners shell
      - name: build
        # 运行构建脚本
        run: bash deploy.sh